### ISSUE TITLE
Dispatching events from Models

### ISSUE THREAD

**Issue by berkayk** [openfl/robotlegs#12]
This was possible in RobotLegs 1. I couldn't find any docs in the Robotlegs' website. I am converting my project which has robotlegs 1 in it. There are tons of events dispatched from models. What would be the easiest way to convert? Is there any method for dispatching from Models (like extending from another class) or is it better to convert all dispatches in models to Signals.

Thanks.

**Comment by peteshand** [comment]
Are you referring to the Robotlegs 1 (AS3 version)?

**Comment by berkayk** [comment]
Yes.

**Comment by peteshand** [comment]
Right, I can't say I'm that familiar with RL1. I'm sure what you're after is achievable.

But I'd suggest looking into using the Notifier haxelib.
https://github.com/berkayk/haxe-openfl-starter-test/pull/1

https://lib.haxe.org/p/notifier/

**Comment by berkayk** [comment]
I managed to dispatch events from the model by injecting `eventDispatcher` and dispatch events from it.

Notifier is a good alternative but I want to make as little changes as possible. If I refactor it later, I will change them to signals.
