### ISSUE TITLE
Robotlegs Macro DescribedType

### ISSUE THREAD

**Issue by peteshand** [openfl/robotlegs#2]
Hey @TomByrne 

I'm getting the following error using targeting HTML5 with the latest Robotlegs and Starling 2.4. 
```
IndexData.hx:73 Uncaught ReferenceError: openfl is not defined
    at IndexData.hx:73
    at IndexData.hx:73
    at ViewConfig.hx:21
EnterFrame.hx:39 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Function.mantle_time_EnterFrame.OnRunningChange (EnterFrame.hx:39)
    at EnterFrame.hx:30
    at haxe_Timer.t.run (Timer.hx:145)
    at Timer.hx:71
```
Is this a combo that you've tried lately? I haven't been able to isolate what is causing the issue, but there is a good chance it has something to do with the Macro DescribedType stuff.

other targets seem to work fine. (AIR, Flash, Electron)

**Comment by TomByrne** [comment]
Hey Pete,
I've just run our example project with Starling 2.4 / Robotlegs 1.1, in HTML, it seems to run fine for me.
Where are you seeing this?

**Comment by peteshand** [comment]
Interesting.. it might be a vscode issue.

**Comment by peteshand** [comment]
or maybe something to do with dce

**Comment by TomByrne** [comment]
I tried with DCE=std and all worked fine.
DCE=full didn't, but I'm getting different errors to what you're seeing here.

**Comment by peteshand** [comment]
yeah, it have been something with my setup.. I'm seeing different behaviour between HaxeDevelop and vscode / window and osx. Anyways it seems to have gone away for now.
